name: doom-infra

services:
  doom-postgres:
    container_name: doom-postgres
    build: .
    restart: unless-stopped
    volumes:
      - "/home/nebula/bkan0n/appdata/doom-postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_USER=${PSQL_USER}
    networks:
      - doom-network
      - caddy-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  doom-postgres-backup:
    image: eeshugerman/postgres-backup-s3:15
    container_name: doom-postgres-backup
    restart: unless-stopped
    environment:
      SCHEDULE: '@daily'
      BACKUP_KEEP_DAYS: 7     # optional
      S3_REGION: us-west-002
      S3_ACCESS_KEY_ID: ${KEY_ID}
      S3_SECRET_ACCESS_KEY: ${KEY_SECRET}
      S3_BUCKET: doom-backups
      S3_PREFIX: backups
      S3_ENDPOINT: ${S3_ENDPOINT}
      POSTGRES_HOST: doom-postgres
      POSTGRES_DATABASE: doom3
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - doom-network

networks:
  doom-network:
    external: true
  caddy-network:
    external: true
