name: doom-infra

services:
  doom-postgres:
    container_name: doom-postgres
    build: ./postgres
    restart: unless-stopped
    ports:
      - "15432:5432"
    volumes:
      - "/home/nebula/bkan0n/appdata/doom-postgres:/var/lib/postgresql/data"
      - "/home/nebula/bkan0n/backups/doom-postgres:/backups"
    environment:
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_USER=${PSQL_USER}
    networks:
      - doom-network
      - caddy-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"

networks:
  doom-network:
    external: true
  caddy-network:
    external: true
